// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDisNReRU0OoMvAvEYMkE5LewBhECbnGj8',
    appId: '1:1096640857187:web:bd5209fbb37f218912e456',
    messagingSenderId: '1096640857187',
    projectId: 'fir-crashlytics-da32f',
    authDomain: 'fir-crashlytics-da32f.firebaseapp.com',
    storageBucket: 'fir-crashlytics-da32f.appspot.com',
    measurementId: 'G-FWDGWLELLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnXhGGjK20VqZRNWALfliZYslSWWz09bs',
    appId: '1:1096640857187:android:d3afae2d4ab23c3312e456',
    messagingSenderId: '1096640857187',
    projectId: 'fir-crashlytics-da32f',
    storageBucket: 'fir-crashlytics-da32f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnc_WYhiuwYWN-zN8NHSfCO2AAKlo5z2g',
    appId: '1:1096640857187:ios:084be4e8ad1cbfe712e456',
    messagingSenderId: '1096640857187',
    projectId: 'fir-crashlytics-da32f',
    storageBucket: 'fir-crashlytics-da32f.appspot.com',
    iosBundleId: 'com.example.firebaseCrashlytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnc_WYhiuwYWN-zN8NHSfCO2AAKlo5z2g',
    appId: '1:1096640857187:ios:1a246d70d944dead12e456',
    messagingSenderId: '1096640857187',
    projectId: 'fir-crashlytics-da32f',
    storageBucket: 'fir-crashlytics-da32f.appspot.com',
    iosBundleId: 'com.example.firebaseCrashlytics.RunnerTests',
  );
}
